### ISSUE TITLE
    print("Could not import one of these modules: pywinauto , colorama , pypresence")

### ISSUE THREAD

**Issue by Altanb1337** [actuallydoc/autofarm-py#1]
print("Could not import one of these modules: pywinauto , colorama , pypresence")

how to fix this error im using 3.9 version of python

**Comment by actuallydoc** [comment]
U are missing some modules as it says ill add a requierments file so u will be able to install all the modules with pip

**Comment by Altanb1337** [comment]
> U are missing some modules as it says ill add a requierments file so u will be able to install all the modules with pip

how to install the modules on windows?

**Comment by actuallydoc** [comment]
i added the requierments.txt to the repository install it put it in the folder and open cmd in the folder and do
pip install -r requirements.txt

**Comment by actuallydoc** [comment]
There is currently a bug and u will have to wait so i fix it otherwise u wont be able to use the autofarm properly.

**Comment by actuallydoc** [comment]
Open Another Issue if you still cannot get it to work

**Comment by Altanb1337** [comment]
which python version do you using?

**Comment by actuallydoc** [comment]
The latest python

**Comment by actuallydoc** [comment]
python 3.9.4
